version = 0.1

[dev]
[dev.deploy]
[dev.global.parameters]
stack_name = "get-and-read-EMHI"

[dev.deploy.parameters]
s3_bucket = "wni-expo-lambda-function-434834903063-eu-central-1"
s3_prefix = "get-and-read-EMHI"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "RawDataBucket=wni-dev-expo-data-ingest-workspace-eu-central-1 ConvertedBucket=wni-wds-dev-global-aqc-apne1 tagid=441000140 URL=https://www.ilmateenistus.ee/ilma_andmed/xml/observations.php"

tags = [
  "map-migrated=\"migMCX7KD5RU8\"",
  "Cost=\"WDSQLT\"",
  "Function=\"wds-data-qc\"",
  "TagID-IN=\"441000140\"",     
  "TagID-OUT=\"441000210/419000211\"",   
  "Administrator=\"sakamo\""
]

[prod]
[prod.deploy]
[prod.global.parameters]
stack_name = "get-and-read-EMHI"

[prod.deploy.parameters]
s3_bucket = "wni-expo-lambda-function-530735221505-eu-central-1"
s3_prefix = "get-and-read-EMHI"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "RawDataBucket=wni-amdeliver-to-stockons3-ap-northeast-1 ConvertedBucket=wni-wds-prod-global-aqc-apne1 tagid=441000140 URL=https://dmigw.govcloud.dk/v2/metObs/collections/observation/items"

tags = [
  "map-migrated=\"migMCX7KD5RU8\"",
  "Cost=\"WDSQLT\"",
  "Function=\"wds-data-qc\"",
  "TagID-IN=\"441000140\"",     
  "TagID-OUT=\"441000210/419000211\"",  
  "Administrator=\"sakamo\""
]