version = 0.1

[dev]
[dev.deploy]
[dev.global.parameters]
stack_name = "convert-DHMZ-data"

[dev.deploy.parameters]
resolve_s3 = true
s3_prefix = "convert-DHMZ-data"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "RawDataBucket=wni-dev-data-ingest-stock-ap-northeast-1 ConvertedBucket=wni-wds-dev-global-aqc-apne1 tagid=441000134 URL=https://vrijeme.hr/hrvatska_n.xml"

tags = [
  "map-migrated=\"migMCX7KD5RU8\"",
  "Cost=\"WDSQLT\"",
  "Function=\"wds-data-qc\"",
  "TagID-IN=\"441000134\"",     
  "Administrator=\"sakamo\""
]

[prod]
[prod.deploy]
[prod.global.parameters]
stack_name = "convert-DHMZ-data"

[prod.deploy.parameters]
resolve_s3 = true
s3_prefix = "convert-DHMZ-data"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "RawDataBucket=wni-data-ingest-stock-ap-northeast-1　ConvertedBucket=wni-wds-prod-global-aqc-apne1 tagid=441000134 URL=https://vrijeme.hr/hrvatska_n.xml"

tags = [
  "map-migrated=\"migMCX7KD5RU8\"",
  "Cost=\"WDSQLT\"",
  "Function=\"wds-data-qc\"",
  "TagID-IN=\"441000134\"",     
  "Administrator=\"sakamo\""
]