version = 0.1

[dev]
[dev.deploy]
[dev.global.parameters]
stack_name = "convert-dwd-synop"

[dev.deploy.parameters]
resolve_s3 = true
s3_prefix = "convert-dwd-synop"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "RawDataBucket=wni-dev-data-ingest-stock-ap-northeast-1 ConvertedBucket=wni-wds-dev-global-aqc-apne1 tagid=441000213 URL=https://opendata.dwd.de/weather/weather_reports/synoptic/germany/json/Z__C_EDZW_latest_bda01,synop_bufr_GER_999999_999999__MW_XXX.json.bz2"

tags = [
  "map-migrated=\"migMCX7KD5RU8\"",
  "Cost=\"WDSQLT\"",
  "Function=\"wds-data-qc\"",    
  "TagID-OUT=\"441000203/441000206\"",   
  "Administrator=\"sakamo\""
]

[prod]
[prod.deploy]
[prod.global.parameters]
stack_name = "convert-dwd-synop"

[prod.deploy.parameters]
resolve_s3 = true
s3_prefix = "convert-ded-synop"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "RawDataBucket=wni-data-ingest-stock-ap-northeast-1 ConvertedBucket=wni-wds-prod-global-aqc-apne1 tagid=441000213 URL=https://opendata.dwd.de/weather/weather_reports/synoptic/germany/json/Z__C_EDZW_latest_bda01,synop_bufr_GER_999999_999999__MW_XXX.json.bz2"

tags = [
  "map-migrated=\"migMCX7KD5RU8\"",
  "Cost=\"WDSQLT\"",
  "Function=\"wds-data-qc\"",   
  "TagID-OUT=\"441000203/441000206\"", 
  "Administrator=\"sakamo\""
]