version = 0.1

[dev]
[dev.deploy]
[dev.global.parameters]
stack_name = "get-inmet-table-merged-json"

[dev.deploy.parameters]
resolve_s3 = true
s3_prefix = "get-inmet-table-merged-json"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
  "MDBucket=wni-wds-dev-global-aqc-apne1"
  ]
tags = [
  "map-migrated=\"migMCX7KD5RU8\"",
  "Cost=\"WDSQLT\"",
  "Function=\"wds-data-qc\"",
  "TagID-IN=\"460320017/460320018\"",     
  "TagID-OUT=\"460320026\"",   
  "Administrator=\"sakamo\""
]

[prod]
[prod.deploy]
[prod.global.parameters]
stack_name = "get-inmet-table-merged-json"
[prod.deploy.parameters]
resolve_s3 = true
s3_prefix = "get-inmet-table-merged-json"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
  "MDBucket=wni-wds-prod-global-aqc-apne1",
  "LambdaSecurityGroup=sg-0bb1b3a3db98e55fe",
  "PrivateSubnet1=subnet-0c889a5e97e32db9e",
  "PrivateSubnet2=subnet-0e86cbeacfd4d8ae9",
  "PrivateSubnet3=subnet-0ccdc645fc107d367"
  ]
tags = [
  "map-migrated=\"migMCX7KD5RU8\"",
  "Cost=\"WDSQLT\"",
  "Function=\"wds-data-qc\"",
  "TagID-IN=\"460320017/460320018\"",     
  "TagID-OUT=\"460320026\"",   
  "Administrator=\"sakamo\""
]